on:
  push:
    tags:
      - v*

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows,android]
        goarch: ["386", amd64, arm64, arm]
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.40
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        compress_assets: "OFF"
